name: Vacancy Management Application

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: termurin
                java-version: 17
            - name: Build project
              run: mvn clean install
            - name: Login docker
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t pedrooliveira465/vacancy_management .
            - name: Publish image
              run: docker push pedrooliveira465/vacancy_management
      deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image docker hub 
              run: docker pull pedrooliveira465/vacancy_management:latest
            - name:  remove container
              run: docker rm -f vacancy-management
            - name: Run docker container vacancy-management
              run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_NAME=${{secrets.DATABASE_NAME}} --name vacancy-management pedrooliveira465/vacancy_management:latest